name= "pastebin-worker"
compatibility_date = "2023-11-28"
account_id= "fac7fb2a2e76a4576667d203f9c9a925"
main = "src/index.ts"
workers_dev = true

vars = { ENVIRONMENT = "production" }
#route = { pattern = " ", custom_domain = true }

kv_namespaces = [
  { binding = "PB", id = "727e208592ac4cdaaa962caebb820349" },
  { binding = "PBIMGS", id ="77d2be2f691b4325a35158c4b01cc50d" }
]

[site]
bucket = "./static/dist"
